### ISSUE TITLE
500 Error when using organization

### ISSUE THREAD

**Issue by xnt** [berkerpeksag/github-badge#51]
When I use an organization instead of a user, it throws a 500 server error... I guess this is more of a feature request than a bug itself, but it'd be nice having it...

**Comment by berkerpeksag** [comment]
We have much better support for organizations now:

<img width="213" alt="Screen Shot 2019-04-19 at 5 46 04 PM" src="https://user-images.githubusercontent.com/26338/56438211-cb0ce500-62ea-11e9-9930-56793cff796a.png">

See https://github.com/berkerpeksag/github-badge/issues/73#issuecomment-484919703 for details. 

Closing this for now. Thank you for the feedback!
