### ISSUE TITLE
Zeros on Stats for Organization

### ISSUE THREAD

**Issue by benmorrow** [berkerpeksag/github-badge#73]
Hi,

Do you know why the stats are zero-ed out on the badge?

![screenshot](https://cloud.githubusercontent.com/assets/5604/3374536/8a734bde-fbbf-11e3-9042-431c6a8b89ef.png)

Organization: https://github.com/happywatch

We should have 1 repo, right?

**Comment by berkerpeksag** [comment]
This seems to be working now:

<img width="213" alt="Screen Shot 2019-04-19 at 5 46 04 PM" src="https://user-images.githubusercontent.com/26338/56429342-3d6dcd00-62cb-11e9-96c4-1dfbc72cb457.png">

<img width="213" alt="Screen Shot 2019-04-19 at 5 46 59 PM" src="https://user-images.githubusercontent.com/26338/56429343-3d6dcd00-62cb-11e9-9d1c-dd4ba4f2fa74.png">

Some features aren't working as expected but we can deal with them in separate issues.

Closing this as 'outdated'. Thank you!
