### ISSUE TITLE
two factor authentication

### ISSUE THREAD

**Issue by michaelstrange** [berkerpeksag/github-badge#80]
How can I use this, when I have two-factor authentication enabled?

**Comment by BYK** [comment]
We only use publicly available information so you shouldn't need to do anything extra?

**Comment by michaelstrange** [comment]
That's what i thought.

But my badge looks very empty :)

http://githubbadge.appspot.com/michaelstrange

**Comment by BYK** [comment]
That's because we don't get stats for any private repos since we only use public information.

**Comment by michaelstrange** [comment]
All my repos are public.. :)

**Comment by BYK** [comment]
All your repos seem quite new (younger than 6 hours). We do rely on heavy caching so give it about 24 to 48 hours to pick up these changes ;)

**Comment by michaelstrange** [comment]
I see. That makes sense. Thank you :)

**Comment by BYK** [comment]
No problem :)
