### ISSUE TITLE
profile pic not updating

### ISSUE THREAD

**Issue by fanshi118** [berkerpeksag/github-badge#85]
I guess this is not that much of a big issue...but when I updated my profile picture on github, the pic on my badge doesn't get updated. It'd be great if you guys can fix this though!

**Comment by houmie** [comment]
+1

**Comment by BYK** [comment]
It should update in about 48 hours max.

**Comment by Ben-PH** [comment]
+1

**Comment by mclim9** [comment]
Same issue.   Tried w/ jpeg & png.  Profile picture does not change.

**Comment by GlitchXploitr** [comment]
same.

**Comment by exawolf** [comment]
Same issue

**Comment by ellis-bigelow** [comment]
Same issue.

**Comment by PranjalGhate** [comment]
so is this github's problem or is it related to image size?

**Comment by N02870941** [comment]
same issue

**Comment by tlewandster** [comment]
same

**Comment by shrutikapoor08** [comment]
Same issue. My file size is > 500 KB and it didnt work. Tried with another picture that was 100KB and it worked.

**Comment by pabrams** [comment]
What's going on?

**Comment by jenoh** [comment]
same

**Comment by bensongathee** [comment]
Same issue here. Could this issue be fixed?

**Comment by berkerpeksag** [comment]
Unfortunately, I don't have time to work on this at the moment. However, I'd be gladly review and merge a PR.

Thank you for using GitHub Badge and sorry for the inconvenience.

**Comment by shrutikapoor08** [comment]
I will be glad to make a PR if you can point me to some helpful resources @berkerpeksag

**Comment by berkerpeksag** [comment]
GitHub Badge is an App Engine application. You will need to install App Engine SDK. All third-party dependencies are located in `packages` directory. You may need to install an older version of the SDK to run the application on your system.

I think we can now delete the following snippet:

https://github.com/berkerpeksag/github-badge/blob/197082f717b25714f09ed503ff31ca2392fa7376/app/core.py#L164-L169

And add `&amp;s=24` after `{{ user.avatar_url }}` in the following line:

https://github.com/berkerpeksag/github-badge/blob/197082f717b25714f09ed503ff31ca2392fa7376/templates/badge.html#L23

**Comment by harsh159357** [comment]
Issue is there but make image size less than 500Kb. Try anything that will make image smaller than 500 Kb. For ex- I tried https://www.reduceimages.com/ and it worked.

**Comment by revanthsenthil** [comment]
I had to make it less than 100kb, only then did it work, as @harsh159357 mentioned, https://www.reduceimages.com/ does this pretty well. The image looks bad and kinda pixelated in the end though.

**Comment by xItzDiamondx** [comment]
Mine is less than 100kb, mine is 3kb

**Comment by jdissimoz-sw** [comment]
In my case, file was only 55.1kb and the badge icon still wasn't updating, until I pressed Ctrl + F5. So besides all they have commented here, part of it is a browser caché issue too.

**Comment by EdenGoforIt** [comment]
same issue here. When I share the git link with others

**Comment by OsamahBaka** [comment]
same here

**Comment by mehrdadmoradi001** [comment]
Note: Your profile picture should be a PNG, JPG, or GIF file, and it must be less than 1 MB in size and smaller than 3000 by 3000 pixels. For the best quality rendering, we recommend keeping the image at about 500 by 500 pixels.

**Comment by cleuton** [comment]
+1

**Comment by zmeyka3310** [comment]
bump

**Comment by jugglingbear** [comment]
Bump, image is 320KB (1024x1024) and does not seem to want to update. I'll wait the 48 hours like one of the first comments said. Maybe it will resolve itself

**Comment by o-sergeneser** [comment]
bump

**Comment by BYK** [comment]
@o-sergeneser the project is mostly abandoned so don't expect fixes at this point. Sorry 😔
