### ISSUE TITLE
API for over quota

### ISSUE THREAD

**Issue by FelixVicis** [berkerpeksag/github-badge#86]
It would be lovely if there was an API call to read when this service is over quota--something simple such as a yes/no response. I would like to be able to use this to hide the badge only when the service is down.

[Documentation for Appengine quotas](https://cloud.google.com/appengine/docs/quotas#When_a_Resource_is_Depleted)

**Comment by BYK** [comment]
Are going over quota too frequently? Isn't it better to fix that problem instead?

**Comment by FelixVicis** [comment]
Ideally, yes. However after reading Issue #76 I assumed that this was a known problem. 

Really, the reason for asking is that I use a badge on my page and would rather be able to change my layout instead of showing the error page.

![image](https://cloud.githubusercontent.com/assets/6580094/14839985/7ef27d84-0be4-11e6-9a30-ab11794c5674.png)

If I could find a work around, I would. But short of loading the badge server-side; I cannot find a way to detect when your service is down.

**Comment by leniel** [comment]
me too

**Comment by berkerpeksag** [comment]
Thank you for the report! This will be resolved by #47.
