### ISSUE TITLE
server error

### ISSUE THREAD

**Issue by gautamkrishnar** [berkerpeksag/github-badge#87]
Error: Server Error
The server encountered an error and could not complete your request.

Please try again in 30 seconds.

See the url: http://githubbadge.appspot.com/gautamkrishnar

**Comment by jayvdb** [comment]
I see the same problem: http://githubbadge.appspot.com/jayvdb

**Comment by jayvdb** [comment]
Maybe related to #76

**Comment by cncoder** [comment]
I see the same problem: https://githubbadge.appspot.com/cncoder

**Comment by gautamkrishnar** [comment]
Still not fixed😢

**Comment by berkerpeksag** [comment]
Closing as a duplicate of #86. Thank you for the all feedback!
